# Header
menu:
  主页: /
  随笔: /archives
  标签云: /tags/


# SubNav
subnav:
  github: "https://github.com/BrokenRain"
  rss: /atom.xml
  #weibo: "#"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root:

language: zh-Hans

# Content
# 文章太长，截断按钮文字
excerpt_link: Read More
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false
# 图片预览
fancybox: true

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.png
alipay: /assets/img/alipay.png
# 微信二维码图片地址
weixin: /assets/img/weixin.png

#开启不算子访问统计
busuanzi:
  enable: true
footer:
  # visitors count设置访问量是否显示
  counter: true

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

#你的头像url
avatar: /assets/blogImg/cat.jpg

#是否开启分享
share_jia: true

mobile:
  social: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#1、多说
#duoshuo: "litten-hexo"

#2、网易云跟帖
#wangyiyun: '2dba06fbf8d24c13915ea6c6aa7183b1'

#3、畅言
changyan_appid: 'cyufrAESa'
changyan_conf: '00d2c6db102a72eb2b40b2e95253c0b7'

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、commenthub
#commenthub_id: 26315848

#6、必力
#livere: 'MTAyMC80NDM1NS8yMDg4Nw=='

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: false
  aboutme: '关于我'

friends:
  友情链接1: http://localhost:4000/
  友情链接2: http://localhost:4000/
  友情链接3: http://localhost:4000/
  友情链接4: http://localhost:4000/
  友情链接5: http://localhost:4000/
  友情链接6: http://localhost:4000/

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /assets/blogImg/favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:

# 添加浏览量
# leancloud_visitors:
#   enable: true
#   app_id: ************** 
#   app_key: ************

#添加一下js插件的 CDN地址
# js_cdn:
#   jquery: https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js
#   av : //cdn1.lncld.net/static/js/2.5.0/av-min.js

aboutme: 那年心碎的雨<br><br>毕业于南昌航空大学 <br>目前只是一个上位机小开发一枚